implements dams preprocessor, implements rake task for dams
emory-libraries/dlp-curate pull request #1519
Opened 2020-10-01 16:26 UTC by alexBLR

2020-10-01 18:19 UTC, devanshu-m requested changes
This looks good, zo. Just one question/change.

2020-10-01 18:19 UTC, devanshu-m commented on spec/fixtures/csv_import/dams/dams-unprocessed.csv
> +,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Are these blank entries necessary? If not can we please get rid of them?

2020-10-02 13:24 UTC, alexBLR commented on spec/fixtures/csv_import/dams/dams-unprocessed.csv
> +,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Thank you for noticing. I removed the empty rows.

2020-10-02 15:06 UTC, devanshu-m approved these changes

2020-10-02 15:06 UTC, merged