Road to Hyrax 3.2.0.
emory-libraries/dlp-curate pull request #1773
Opened 2022-02-16 20:45 UTC by bwatson78

2022-02-24 19:56 UTC, rotated8 commented
The decrease in code coverage is acceptable to me.

2022-02-25 18:20 UTC, abelemlih requested changes
@bwatson78 looks great! I added a few comments/questions. 

One thing I noticed in particular is the use of `3.0.0` and `3.1.0` in files we are overwriting, instead of `3.3.0` which is the version we are upgrading to. Could please go through all the files we are overwriting, and update them with the correct version?

2022-02-25 18:20 UTC, abelemlih commented on spec/factories/collections.rb
> +# [Hyrax-overwrite-v3.1.0 (This may have to change for v3.2.0)]
We need to update the overwrite to `3.3.0`. Also, is any change needed for 3.3.0?

2022-02-25 18:20 UTC, abelemlih commented on spec/jobs/attach_files_to_work_job_spec.rb
> +      # The following line may have to change for Hyrax v3.3.0.
Is this comment still relevant?

2022-02-25 18:20 UTC, abelemlih commented on spec/models/collection_spec.rb
> +      # The code below may need to change.
Is this comment still relevant?

2022-02-25 18:20 UTC, abelemlih commented on spec/system/create_curate_generic_work_spec.rb
> +      # TODO: If you generate more than one work uncomment these lines
Is this `todo` still relevant?

2022-02-25 18:24 UTC, abelemlih commented
@bwatson78 Another thing we could do, if possible, is squash these commits into one `upgrade hyrax to 3.3.0` commit for instance, to prevent having a long list of comments in history that all pertain to this one particular change. If we cannot have one commit, could we at least just reduce the number of commits by grouping some changes together, that way the commit history is cleaner once we merge this PR.

2022-02-25 19:48 UTC, bwatson78 commented on app/helpers/hyrax/file_set_override_helper.rb
> +  # @todo inline the "workflow restriction" into the `can?(:download)` check.
This was another inclusion by Samvera's contributors. Since they added the comment, I thought that it would benefit us to transfer it to our override so that didn't have to go hunting for it later.

2022-02-25 19:54 UTC, bwatson78 commented on app/jobs/characterize_job.rb
> +      self.class.characterization_service
This is another case where I felt it was better to mimic the structure that Samvera created to make it easier to compare the differences using `git diff`, for example. I agree with you, I wouldn't make it a private method myself--but trying to keep things as close to the original file, I believe, has benefits.

2022-02-25 20:54 UTC, bwatson78 commented
@abelemlih I believe I've addressed all your requests. Let me know if you have opinions on my responses.

2022-02-28 16:41 UTC, abelemlih approved these changes
Looks great, thanks for making all the edits!

2022-02-28 16:46 UTC, merged