Fixes the Pub Key error showing in the Install Python2 process.
emory-libraries/dlp-curate pull request #1845
Opened 2022-07-12 16:23 UTC by bwatson78

2022-07-12 16:35 UTC, bwatson78 commented
@rotated8 This change fixes the error, but is the change safe for deployment?

2022-07-12 18:44 UTC, rotated8 requested changes
Can we split the one line into two?

2022-07-12 18:44 UTC, rotated8 commented on .circleci/config.yml
> +                command: sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4EB27DB2A3B88B8B && sudo apt-get update && sudo apt-get install -y python2
Does this work if it's split into two lines?
```suggestion
                command: sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4EB27DB2A3B88B8B
                command: sudo apt-get update && sudo apt-get install -y python2
```

2022-07-12 18:49 UTC, rotated8 commented on .circleci/config.yml
> +                command: sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4EB27DB2A3B88B8B && sudo apt-get update && sudo apt-get install -y python2
Wait, no, that won't work.

2022-07-12 18:55 UTC, rotated8 requested changes
I think I fixed the syntax. I think this should work?

2022-07-12 18:55 UTC, rotated8 commented on .circleci/config.yml
> +                command: sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4EB27DB2A3B88B8B && sudo apt-get update && sudo apt-get install -y python2
```suggestion
                command: |
                    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4EB27DB2A3B88B8B
                    sudo apt-get update && sudo apt-get install -y python2
```

2022-07-12 18:56 UTC, bwatson78 commented on .circleci/config.yml
> +                command: sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4EB27DB2A3B88B8B && sudo apt-get update && sudo apt-get install -y python2
I'll give it a shot.

2022-07-12 19:48 UTC, bwatson78 commented on .circleci/config.yml
> +                command: sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4EB27DB2A3B88B8B && sudo apt-get update && sudo apt-get install -y python2
Last commit should address your request.

2022-07-26 21:55 UTC, rotated8 commented
@bwatson78 I think this PR is no longer necessary, correct?

2022-07-26 23:46 UTC, bwatson78 commented
Right.

2022-07-26 23:46 UTC, closed without merging