Upgrades to  Hyrax v3.4.2.
emory-libraries/dlp-curate pull request #1964
Opened 2022-09-14 19:01 UTC by bwatson78

2022-11-01 20:51 UTC, abelemlih requested changes
Minor comments that @bwatson78 and I can address

2022-11-01 20:51 UTC, abelemlih commented on app/controllers/hyrax/curate_generic_works_controller.rb
> +          curation_concern # This is here for authorization checks (we could add authorize! but let's use the same method for CanCanCan)
I am not sure what exactly is the purpose of this method, can you please provide additional details of why this line is necessary? Also, is there a way to avoid having the instance variable `@curation_concern` and the method `#curation_concern` be named the same

2022-11-01 20:51 UTC, abelemlih commented on app/jobs/README.md
> +The creation of curation objects inside of Hyrax depends upon a custom-built [Rack Middleware Stack](https://guides.rubyonrails.org/rails_on_rack.html). In essence, it is a coding design pattern that
We need to replace all mentions of `3.4.1` to `3.4.2` in this file

2022-11-01 20:51 UTC, abelemlih commented on app/builders/curate_manifest_helper.rb
> +  # Build a rendering hash (logic and method taken from Hyrax-v3.4.1, except host resolution)
Replace with 3.4.2

2022-11-01 20:51 UTC, abelemlih commented on app/lib/curate_collection_behavior.rb
> +  # Hyrax v3.4.1 Override: reverting back to the non-Valkrie processing because
Replace with 3.4.2

2022-11-01 20:51 UTC, abelemlih commented on app/search_builders/hyrax/multi_level_collection_member_search_builder.rb
> +# [Hyrax-overwrite-v3.1.0] Modify #member_of_collection to also search against a source collection's deposit collections
Is this an overwrite of `3.1.0` or `3.4.2`?

2022-11-01 20:51 UTC, abelemlih commented on app/views/zizia/csv_imports/_collection_selection.html.erb
> +<!-- [Zizia-overwrite-v6.0.1] ActiveFedora Solr query was producing a list without all Collections, so
Zizia is locked to `v5.5.0` in the `Gemfile`, is this overwrite still accurate?

2022-11-01 20:51 UTC, abelemlih commented on config/initializers/collection_member_search_service_overrides.rb
> +# [Hyrax-overwrite-v3.1.0] overrides the initialize method to use the
Is this overwrite still relevant for `3.4.2`? if so, we need to update the comment

2022-11-01 20:51 UTC, abelemlih commented on config/puma.rb
> +# pidfile ENV.fetch("PIDFILE") { "tmp/pids/server.pid" }
Is this comment still needed?

2022-11-02 13:18 UTC, alexBLR submitted a review, later dismissed

2022-11-02 14:52 UTC, bwatson78 commented on app/controllers/hyrax/curate_generic_works_controller.rb
> +          curation_concern # This is here for authorization checks (we could add authorize! but let's use the same method for CanCanCan)
That's easy. The reason this portion of code has changed is because it changed in Hyrax' progression of code (see [here](https://github.com/samvera/hyrax/blob/a0f8455fa373b94f2700b0a47fd55084ba7fde6d/app/controllers/concerns/hyrax/works_controller_behavior.rb#L81). It's a pure swap out that makes seeing our code changes and the core Hyrax code obvious.
![Screen Shot 2022-11-02 at 10 50 32 AM](https://user-images.githubusercontent.com/18330149/199521794-62846eeb-ea0b-4876-8260-4145afcce263.png)
My intention is to keep all methods mirrored to the overridden Hyrax code besides our own changes so that it's easier to tell the differences the next multiple times we upgrade Hyrax.

2022-11-02 15:12 UTC, bwatson78 commented on app/views/zizia/csv_imports/_collection_selection.html.erb
> +<!-- [Zizia-overwrite-v6.0.1] ActiveFedora Solr query was producing a list without all Collections, so
Corrected in #2021

2022-11-02 18:57 UTC, abelemlih approved these changes

2022-11-02 19:02 UTC, merged